/**
 * Document Model for VTRIA ERP
 * Manages file uploads, document generation and versioning
 */

module.exports = (sequelize, DataTypes) => {
  const Document = sequelize.define('Document', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true
    },
    filename: {
      type: DataTypes.STRING,
      allowNull: false
    },
    original_name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    file_path: {
      type: DataTypes.STRING,
      allowNull: false
    },
    file_size: {
      type: DataTypes.BIGINT
    },
    mime_type: {
      type: DataTypes.STRING
    },
    document_type: {
      type: DataTypes.ENUM('ENQUIRY', 'QUOTATION', 'PURCHASE_ORDER', 'INVOICE', 'TECHNICAL', 'REPORT', 'CASE_ATTACHMENT', 'OTHER'),
      defaultValue: 'OTHER'
    },
    document_number: {
      type: DataTypes.STRING,
      comment: 'Standardized document ID (e.g., VESPL/EQ/2526/001)'
    },
    document_date: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW
    },
    version_count: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      comment: 'Number of versions this document has'
    },
    case_id: {
      type: DataTypes.UUID,
      references: {
        model: 'cases',
        key: 'id'
      }
    },
    uploaded_by: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'users',
        key: 'id'
      }
    },
    is_public: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },
    tags: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: []
    },
    metadata: {
      type: DataTypes.JSONB,
      defaultValue: {}
    },
    is_generated: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      comment: 'Whether this document was generated by the system'
    },
    template_used: {
      type: DataTypes.STRING,
      comment: 'Template used for document generation'
    },
    ticket_id: {
      type: DataTypes.UUID,
      references: {
        model: 'tickets',
        key: 'id'
      }
    }
  }, {
    tableName: 'documents',
    indexes: [
      { fields: ['case_id'] },
      { fields: ['uploaded_by'] },
      { fields: ['document_type'] }
    ]
  });

  return Document;
};
